### ISSUE TITLE
Increase default timeout for SW-PublicationQuery

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#109]
Increase the default timeout for SW-PublicationQuery, see squash details at:
- https://sul-squash.stanford.edu/projects/sul-pub/environments/cap-dev/bugs/2/occurrences
- https://sul-squash.stanford.edu/projects/sul-pub/environments/cap-qa/bugs/6#occurrences

Related code:
- https://github.com/sul-dlss/sul_pub/blob/master/lib/science_wire/request.rb#L14
- https://github.com/sul-dlss/sul_pub/blob/master/lib/science_wire/request.rb#L43

The traceback is not providing enough information to determine whether the timeout is an open timeout or a request timeout, e.g.
- https://sul-squash.stanford.edu/projects/sul-pub/environments/cap-dev/bugs/2/occurrences/4#backtrace

The squash git-blame indicates the timeout is 100, see
https://sul-squash.stanford.edu/projects/sul-pub/environments/cap-qa/bugs/6#blame

However, the master branch code has a timeout of 300, see
https://github.com/sul-dlss/sul_pub/blob/master/lib/science_wire/request.rb#L14

**Comment by drh-stanford** [comment]
From the `cap-qa` logs during the fortnighly harvest, it's happening in the `send_publication_query` method:

```
E, [2016-06-17T04:10:10.553155 #9757] ERROR -- : ScienceWireClient: Faraday::TimeoutError during ScienceWire Publication Query API P
OST request
E, [2016-06-17T04:10:10.553338 #9757] ERROR -- : #<Faraday::TimeoutError>
E, [2016-06-17T04:10:10.553420 #9757] ERROR -- : /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:57:in `sysread
'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:57:in `fill_rbuff'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:204:in `gets'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/ssl_socket.rb:74:in `gets'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:792:in `block in parse_header'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:788:in `parse_header'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:771:in `read_header'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:547:in `get_header'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1294:in `do_get_header'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1241:in `do_get_block'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/httpclient.rb:36:in `call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/request.rb:53:in `response'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/request.rb:25:in `perform'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/api/publication_query.rb:25:in `send_publication_query'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/client.rb:13:in `send_publication_query'
```

The deployed code is using `300` (seconds) for the timeout in `lib/science_wire/request.rb`
