### ISSUE TITLE
Faraday::ClientError during fortnighly_harvest

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul_pub#110]
We're seeing `Faraday::ClientError` exceptions during the author harvesting for `sw:fortnighly_harvest`:

```
E, [2016-06-17T09:01:48.355026 #9757] ERROR -- : ScienceWireClient: Faraday::ClientError during ScienceWire Publication Query API PO
ST request
...
E, [2016-06-17T09:01:50.235762 #9757] ERROR -- : ScienceWireHarvester: Harvest failed for Author.find_by(id: 63429, cap_profile_id: 
88646)
E, [2016-06-17T09:01:50.235869 #9757] ERROR -- : #<Faraday::ClientError>
E, [2016-06-17T09:01:50.235932 #9757] ERROR -- : /opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/respon
se/raise_error.rb:13:in `on_complete'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/request.rb:53:in `response'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/request.rb:25:in `perform'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/api/publication_query.rb:25:in `send_publication_query'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/client.rb:13:in `send_publication_query'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_client.rb:202:in `send_sciencewire_publication_request'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_client.rb:190:in `query_sciencewire'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_client.rb:39:in `query_sciencewire_by_author_name'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/harvest_broker.rb:58:in `ids_from_dumb_query'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/harvest_broker.rb:34:in `ids_for_author'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire/harvest_broker.rb:22:in `generate_ids'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_harvester.rb:141:in `harvest_for_author'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_harvester.rb:32:in `block in harvest_pubs_for_authors'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block (2 levels
) in find_each'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `each'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block in find_e
ach'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `each'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block in find_e
ach'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:50:in `find_each'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_harvester.rb:24:in `harvest_pubs_for_authors'
/opt/app/pub/sul-pub/releases/20160615160318/lib/science_wire_harvester.rb:55:in `harvest_pubs_for_all_authors'
/opt/app/pub/sul-pub/releases/20160615160318/lib/tasks/sw.rake:20:in `block (2 levels) in <top (required)>'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/bin/rake:23:in `load'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
```

**Comment by drh-stanford** [comment]
This (or a related error) is happening in production too on fortnightly harvest.

```
E, [2016-06-16T08:53:49.864416 #19013] ERROR -- : Error for Yu - sul author id: 59012 -  #<Net::ReadTimeout: Net::ReadTimeout>
E, [2016-06-16T08:53:49.864581 #19013] ERROR -- : /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in 
rbuf_fill'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:853:in `start'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_client.rb:334:in `block in send_sciencewire_publication_request'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_client.rb:417:in `with_timeout_handling'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_client.rb:319:in `send_sciencewire_publication_request'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_client.rb:313:in `query_sciencewire'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_client.rb:162:in `query_sciencewire_by_author_name'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_harvester.rb:142:in `harvest_for_author'
/opt/app/pub/sul-pub/releases/20160512033754/lib/science_wire_harvester.rb:30:in `block in harvest_pubs_for_authors'
```
