### ISSUE TITLE
`Author.fetch_from_cap_and_create` should check for a 404 response from the CapHttpClient

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_pub#28]
_From @darrenleeweber on April 1, 2016 1:5_

The `Author.fetch_from_cap_and_create` does not handle 404 from CAP API in
- https://github.com/sul-dlss/sul-pub/blob/complete-authorship-specs/app/models/author.rb#L80-L86

For example,

``` ruby
profile_hash = CapHttpClient.new.get_auth_profile("999999")
=> {"meta"=>{"status"=>404, "message"=>"Object of class [edu.stanford.irt.cap.api.domain.AuthorEntity] with identifier [999999]: not found"}}
```

This CAP API response is not checked for it's status and the method continues to create a new `Author`.  But when it tries to assign values to fields, it fails and hits a `NoMethodError`.

_Copied from original issue: sul-dlss/sul-pub#185_

**Comment by mejackreed** [comment]
_From @darrenleeweber on May 11, 2016 21:51_

Additional exceptions might be handled, for example:
```ruby
> Author.fetch_from_cap_and_create(99)
NoMethodError: undefined method `[]' for nil:NilClass
from /data/src/dlss/cap/sul-pub/app/models/author.rb:146:in `build_attribute_hash_from_cap_profile'
```

```
E, [2016-04-14T14:45:20.567384 #15271] ERROR -- : #<EOFError: end of file reached>
E, [2016-04-14T14:45:20.567616 #15271] ERROR -- : #<EOFError: end of file reached>
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/openssl/buffering.rb:182:in `sysread_nonblock'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/openssl/buffering.rb:182:in `read_nonblock'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:853:in `start'
/home/dlweber/.rbenv/versions/2.2.4/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/data/src/dlss/cap/sul-pub/lib/cap_http_client.rb:26:in `generate_token'
/data/src/dlss/cap/sul-pub/lib/cap_http_client.rb:14:in `initialize'
/data/src/dlss/cap/sul-pub/app/models/author.rb:81:in `new'
/data/src/dlss/cap/sul-pub/app/models/author.rb:81:in `fetch_from_cap_and_create'
```

This one is not exactly the same, with regard to the backtrace, but may also be possible on this call:
```
E, [2016-04-14T13:01:13.318912 #14151] ERROR -- : #<RuntimeError: Server error on authorship call - 2016-04-14 20:01:13 UTC - message from server: { "meta": {  "status": 500, "message":"Uncategorized exception occured during LDAP processing; nested exception is javax.naming.NamingException: LDAP response read timed out, timeout used:5000ms." } }
>
E, [2016-04-14T13:01:13.319200 #14151] ERROR -- : #<RuntimeError: Server error on authorship call - 2016-04-14 20:01:13 UTC - message from server: { "meta": {  "status": 500, "message":"Uncategorized exception occured during LDAP processing; nested exception is javax.naming.NamingException: LDAP response read timed out, timeout used:5000ms." } }
>
/data/src/dlss/cap/sul-pub/lib/cap_http_client.rb:79:in `block in make_cap_request'
/data/src/dlss/cap/sul-pub/lib/cap_http_client.rb:68:in `times'
/data/src/dlss/cap/sul-pub/lib/cap_http_client.rb:68:in `make_cap_request'
/data/src/dlss/cap/sul-pub/lib/cap_http_client.rb:45:in `get_batch_from_cap_api'
```
