### ISSUE TITLE
WOS Harvest bug - PubMed client timeout

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#548]
e.g. for `WOS:000398858600010`
```
E, [2017-12-12T13:30:06.178474 #7394] ERROR -- : WebOfScience::ProcessRecords: WOS:000398858600010 failed to create Publication
E, [2017-12-12T13:30:06.178728 #7394] ERROR -- : #<Faraday::TimeoutError wrapped=#<HTTPClient::ConnectTimeoutError: execution expired>>
E, [2017-12-12T13:30:06.179007 #7394] ERROR -- : /opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `connect'

<snipped htttpclient callbacks>

/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/adapter/httpclient.rb:38:in `call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/request/retry.rb:116:in `call'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
/opt/app/pub/sul-pub/releases/20171212211101/lib/pubmed_client.rb:29:in `fetch_records_for_pmid_list'
/opt/app/pub/sul-pub/releases/20171212211101/app/models/pubmed_source_record.rb:45:in `get_and_store_records_from_pubmed'
/opt/app/pub/sul-pub/releases/20171212211101/app/models/pubmed_source_record.rb:30:in `get_pubmed_record_from_pubmed'
/opt/app/pub/sul-pub/releases/20171212211101/app/models/pubmed_source_record.rb:25:in `for_pmid'
```

**Comment by darrenleeweber** [comment]
There might be a mistake in associating `WOS:000398858600010` with the PubMed client timeout, because that record has no PMID.
```xml
      <identifiers>
        <identifier type='issn' value='1057-9249'/>
        <identifier type='eissn' value='1099-1611'/>
        <identifier type='doi' value='10.1002/pon.4042'/>
      </identifiers>
```

**Comment by darrenleeweber** [comment]
@peetucket - let's revisit this issue if the error is consistent and always connected to a WOS record (possibly the same record).  As it is, there is not enough information yet to clearly determine what to fix.
