### ISSUE TITLE
WOS Harvest bug - exception in pubmed additions

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#549]
```
E, [2017-12-12T13:37:27.941743 #7394] ERROR -- : WebOfScience::ProcessRecords: WOS:000415210700608 failed to create Publication
E, [2017-12-12T13:37:27.941938 #7394] ERROR -- : #<RuntimeError: Failed to create a PubmedSourceRecord for PMID: WOS:000415210700608, 27361328>
E, [2017-12-12T13:37:27.942048 #7394] ERROR -- : /opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/process_records.rb:118:in `pubmed_additions'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/process_records.rb:99:in `create_publication'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/process_records.rb:41:in `block in create_publications'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/process_records.rb:41:in `map'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/process_records.rb:41:in `create_publications'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/process_records.rb:21:in `execute'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/harvester.rb:83:in `process_records'
/opt/app/pub/sul-pub/releases/20171212211101/lib/web_of_science/harvester.rb:27:in `process_author'
```

**Comment by darrenleeweber** [comment]
This is weird, there is no PMID for that record.
```
[12] pry(main)> rec = WebOfScience.queries.retrieve_by_id('WOS:000415210700608').first;
I, [2017-12-13T13:32:35.924735 #29676]  INFO -- : SOAP request: http://search.webofknowledge.com/esti/wokmws/ws/WokSearch
I, [2017-12-13T13:32:35.924887 #29676]  INFO -- : Cookie: SID="5FDyqdp7dmpPs6TJViW", SOAPAction: , Content-Type: text/xml;charset=UTF-8, Content-Length: 714
I, [2017-12-13T13:32:36.303937 #29676]  INFO -- : SOAP response (status 200)
[13] pry(main)> rec.pub_hash[:identifier]
=> [{:type=>"doi", :id=>"10.1249/01.mss.0000487261.91993.b7", :url=>"https://dx.doi.org/10.1249/01.mss.0000487261.91993.b7"},
 {:type=>"eissn", :id=>"1530-0315", :url=>"http://searchworks.stanford.edu/?search_field=advanced&number=1530-0315"},
 {:type=>"issn", :id=>"0195-9131", :url=>"http://searchworks.stanford.edu/?search_field=advanced&number=0195-9131"},
 {:type=>"WosItemID", :id=>"000415210700608", :url=>"https://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/000415210700608"},
 {:type=>"WosUID", :id=>"WOS:000415210700608"}]
[14] pry(main)> rec.pmid
=> nil
```

**Comment by darrenleeweber** [comment]
The PMID might be retrieved from the Links service.  Some bugs in that integration process should be fixed in #551
