### ISSUE TITLE
WOS Harvest exception for PMID: 27963929

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#640]
Failed to find a PubMed record in
- `/lib/web_of_science/process_records.rb:117`
- `pubmed_record = PubmedSourceRecord.for_pmid(record.pmid)`
- `Author: 6, WOS:000276606606255, PubmedSourceRecord failed, PMID: 27963929`

At this point in the harvest, this WOS record contribution for this author already exists.  When the harvest runs again, it will skip this WOS record.  In this scenario, the harvest will never touch this record again.  If there is a PMID record that exists, it will never get integrated by the harvest.  If it doesn't exist, that explains the failure (it's a WOS/Medline data problem?).  The harvest process is designed to be resilient to this failure, it should isolate this exception to just that record and continue (this appears to be true but could be confirmed in some sandbox testing).

#### Note
When calling `PubmedSourceRecord.for_pmid(record.pmid)`, it tries to find it in our records or fetch it from PubMed, i.e.
```
  def self.for_pmid(pmid)
    find_by(pmid: pmid) || get_pubmed_record_from_pubmed(pmid)
  end
```

#### Backtrace

This exception should be registered with Honeybager, but it didn't make it there:
- https://app.honeybadger.io/projects/50046/faults?sort=last_seen_desc&q=environment%3A%22development%22

```
E, [2018-01-19T18:10:39.337083 #11131] ERROR -- : WebOfScience::ProcessRecords: Author: 6, WOS:000276606606255, PubmedSourceRecord failed, PMID: 27963929
E, [2018-01-19T18:10:39.346585 #11131] ERROR -- : #<NoMethodError: undefined method `source_as_hash' for nil:NilClass>
E, [2018-01-19T18:10:39.346828 #11131] ERROR -- : /opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:117:in `pubmed_addition'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:104:in `block in pubmed_additions'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:104:in `each'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:104:in `pubmed_additions'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:47:in `create_publications'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/process_records.rb:22:in `execute'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:91:in `process_records'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:78:in `process_uids'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:33:in `process_author'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:16:in `block in harvest'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:15:in `each'
/opt/app/pub/sul-pub/releases/20180120002105/lib/web_of_science/harvester.rb:15:in `harvest'
/opt/app/pub/sul-pub/releases/20180120002105/lib/harvester/base.rb:9:in `block in harvest_all'
```

**Comment by darrenleeweber** [comment]
```ruby
$ bundle exec rake wos:links['WOS:000276606606255']
{
  "WOS:000276606606255": {
    "sourceURL": "http://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=PARTNER_APP&SrcAuth=LinksAMR&KeyUT=WOS:000276606606255&DestLinkType=FullRecord&DestApp=ALL_WOS&UsrCustomerID=269fc60adb004b0b719031a97aedf5e9",
    "vol": "27",
    "issn": "0732-183X",
    "issue": "15",
    "year": "2009",
    "citingArticlesURL": "http://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=PARTNER_APP&SrcAuth=LinksAMR&KeyUT=WOS:000276606606255&DestLinkType=CitingArticles&DestApp=ALL_WOS&UsrCustomerID=269fc60adb004b0b719031a97aedf5e9",
    "tpages": "2",
    "timesCited": "1",
    "pmid": "27963929",
    "title": "A phase III randomized prospective trial of the effect of psychotherapy on distress in 287 prostate cancer patients: A URCC CCOP Study",
    "ut": "000276606606255"
  }
}
```

**Comment by darrenleeweber** [comment]
```ruby
$ bundle exec rake wos:publication['WOS:000276606606255']
<?xml version='1.0'?>
<REC r_id_disclaimer='ResearcherID data provided by Clarivate Analytics'>
  <UID>WOS:000276606606255</UID>
  <static_data>
    <summary>
      <EWUID>
        <WUID coll_id='WOS'/>
        <edition value='WOS.SCI'/>
        <edition value='WOS.SSCI'/>
        <edition value='WOS.ISTP'/>
      </EWUID>
      <pub_info sortdate='2009-05-20' pubyear='2009' has_abstract='N' coverdate='MAY 20 2009' pubmonth='MAY 20' vol='27' issue='15' supplement='S' pubtype='Journal'>
        <page begin='CP28' end='U221' page_count='2'>CP28-U221</page>
      </pub_info>
      <titles count='6'>
        <title type='source'>JOURNAL OF CLINICAL ONCOLOGY</title>
        <title type='source_abbrev'>J CLIN ONCOL</title>
        <title type='abbrev_iso'>J. Clin. Oncol.</title>
        <title type='abbrev_11'>J CL ONCOL</title>
        <title type='abbrev_29'>J CLIN ONCOL</title>
        <title type='item'>
          A phase III randomized prospective trial of the effect of
          psychotherapy on distress in 287 prostate cancer patients: A URCC CCOP
          Study
        </title>
      </titles>

     etc etc

    <cluster_related>
      <identifiers>
        <identifier type='issn' value='0732-183X'/>
        <identifier type='meeting_abs' value='9637'/>
      </identifiers>
    </cluster_related>
  </dynamic_data>
</REC>
```

**Comment by darrenleeweber** [comment]
There are hundreds of PubMed records that failed in the first (partial) WOS harvest.  From the log file:

```
$ grep 'PubmedSourceRecord failed' web_of_science.log-20180124 
E, [2018-01-22T21:52:37.878315 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 71, WOS:000276606600060, PubmedSourceRecord failed, PMID: 27962535
E, [2018-01-22T21:53:40.911695 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 73, WOS:000208880303405, PubmedSourceRecord failed, PMID: 28023516
E, [2018-01-22T22:06:31.056761 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 82, WOS:000402364400031, PubmedSourceRecord failed, PMID: 28046527
E, [2018-01-22T22:06:48.640283 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 82, WOS:000336849902332, PubmedSourceRecord failed, PMID: 28519565
E, [2018-01-22T22:06:50.239523 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 82, WOS:000336849901237, PubmedSourceRecord failed, PMID: 28519704
E, [2018-01-22T22:13:26.684686 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 105, WOS:000208880302012, PubmedSourceRecord failed, PMID: 28019999
E, [2018-01-22T22:24:50.278448 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 126, WOS:000398590400049, PubmedSourceRecord failed, PMID: 27969888
E, [2018-01-22T22:40:25.663351 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 141, WOS:000208880304625, PubmedSourceRecord failed, PMID: 28023503
E, [2018-01-22T22:59:26.760040 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 163, WOS:000209849300080, PubmedSourceRecord failed, PMID: 27982842
E, [2018-01-22T22:59:40.237155 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 163, WOS:000276606603390, PubmedSourceRecord failed, PMID: 27962823
E, [2018-01-22T23:05:51.755582 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 169, WOS:000208880302126, PubmedSourceRecord failed, PMID: 28020258
E, [2018-01-22T23:18:35.102823 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 188, WOS:000336849900308, PubmedSourceRecord failed, PMID: 28518815
E, [2018-01-22T23:18:43.337787 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 188, WOS:000336849901226, PubmedSourceRecord failed, PMID: 28519689
E, [2018-01-22T23:22:26.546770 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 198, WOS:000276606602227, PubmedSourceRecord failed, PMID: 27964371
E, [2018-01-22T23:22:28.646735 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 198, WOS:000208880301304, PubmedSourceRecord failed, PMID: 28019885
E, [2018-01-22T23:22:29.101620 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 198, WOS:000276606602226, PubmedSourceRecord failed, PMID: 27964375
E, [2018-01-22T23:35:12.810671 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 217, WOS:000223512402588, PubmedSourceRecord failed, PMID: 28014252
E, [2018-01-22T23:35:13.809198 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 217, WOS:000402125900040, PubmedSourceRecord failed, PMID: 28046932
E, [2018-01-22T23:35:40.096079 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 217, WOS:000208880301651, PubmedSourceRecord failed, PMID: 28021460
E, [2018-01-22T23:36:07.938201 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 217, WOS:000402319800045, PubmedSourceRecord failed, PMID: 28048601
E, [2018-01-22T23:36:29.284231 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 217, WOS:000208880301700, PubmedSourceRecord failed, PMID: 28021318
E, [2018-01-22T23:49:21.602439 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 230, WOS:000235246000103, PubmedSourceRecord failed, PMID: 28180457
E, [2018-01-22T23:50:56.373329 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 232, WOS:000208880301324, PubmedSourceRecord failed, PMID: 28022395
E, [2018-01-22T23:51:22.202988 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 232, WOS:000346901000272, PubmedSourceRecord failed, PMID: 28172177
E, [2018-01-22T23:51:24.026589 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 232, WOS:000208880302349, PubmedSourceRecord failed, PMID: 28023570
E, [2018-01-22T23:59:52.590442 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 255, WOS:000336849902249, PubmedSourceRecord failed, PMID: 28519087
E, [2018-01-23T00:06:54.766299 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000208880600155, PubmedSourceRecord failed, PMID: 27957951
E, [2018-01-23T00:06:55.230389 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000276606606527, PubmedSourceRecord failed, PMID: 27962589
E, [2018-01-23T00:06:55.675234 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000276606603402, PubmedSourceRecord failed, PMID: 27962796
E, [2018-01-23T00:07:16.902347 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000223512400415, PubmedSourceRecord failed, PMID: 28014664
E, [2018-01-23T00:07:18.795746 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000208847100015, PubmedSourceRecord failed, PMID: 27985793
E, [2018-01-23T00:07:19.211738 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000208880301134, PubmedSourceRecord failed, PMID: 28023605
E, [2018-01-23T00:07:44.110290 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000239009403461, PubmedSourceRecord failed, PMID: 27955354
E, [2018-01-23T00:07:45.270092 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000208880300466, PubmedSourceRecord failed, PMID: 28020511
E, [2018-01-23T00:07:45.750213 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000276606603094, PubmedSourceRecord failed, PMID: 27962690
E, [2018-01-23T00:08:01.763534 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 279, WOS:000208847100176, PubmedSourceRecord failed, PMID: 27985687
E, [2018-01-23T00:43:24.835195 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 302, WOS:000208880301586, PubmedSourceRecord failed, PMID: 28023688
E, [2018-01-23T00:48:17.625621 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 311, WOS:000208880302527, PubmedSourceRecord failed, PMID: 28019832
E, [2018-01-23T00:48:18.245749 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 311, WOS:000276606606500, PubmedSourceRecord failed, PMID: 27962547
E, [2018-01-23T00:48:22.973246 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 311, WOS:000223512403179, PubmedSourceRecord failed, PMID: 28014530
E, [2018-01-23T00:52:10.716657 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 319, WOS:000223512402280, PubmedSourceRecord failed, PMID: 28016203
E, [2018-01-23T00:52:31.195909 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 319, WOS:000276606605410, PubmedSourceRecord failed, PMID: 27960851
E, [2018-01-23T00:52:49.448047 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 319, WOS:000239009402563, PubmedSourceRecord failed, PMID: 27955334
E, [2018-01-23T00:52:50.546166 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 319, WOS:000223512402286, PubmedSourceRecord failed, PMID: 28016184
E, [2018-01-23T01:16:34.904931 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 324, WOS:000402328800033, PubmedSourceRecord failed, PMID: 28048651
E, [2018-01-23T01:16:35.353253 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 324, WOS:000402319800019, PubmedSourceRecord failed, PMID: 28047985
E, [2018-01-23T01:27:37.361625 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 344, WOS:000208880301541, PubmedSourceRecord failed, PMID: 28023778
E, [2018-01-23T01:27:52.041831 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 344, WOS:000208880301437, PubmedSourceRecord failed, PMID: 28022189
E, [2018-01-23T01:53:49.942634 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 371, WOS:000365807600008, PubmedSourceRecord failed, PMID: 26586484
E, [2018-01-23T01:54:10.397480 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 371, WOS:000365807600010, PubmedSourceRecord failed, PMID: 26577507
E, [2018-01-23T02:40:36.315595 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 383, WOS:000398590400257, PubmedSourceRecord failed, PMID: 27970119
E, [2018-01-23T02:40:36.875968 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 383, WOS:000397332900035, PubmedSourceRecord failed, PMID: 27969687
I, [2018-01-23TE, [2018-01-23T07:34:26.802072 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 748, WOS:000208880302138, PubmedSourceRecord failed, PMID: 28020216
E, [2018-01-23T07:34:27.268441 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 748, WOS:000208880301493, PubmedSourceRecord failed, PMID: 28022568
E, [2018-01-23T08:05:57.614308 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 803, WOS:000336849900406, PubmedSourceRecord failed, PMID: 28518652
E, [2018-01-23T08:10:19.288548 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 813, WOS:A1988N452900044, PubmedSourceRecord failed, PMID: 17731723
E, [2018-01-23T08:35:16.854325 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 816, WOS:000208880700104, PubmedSourceRecord failed, PMID: 27968683
E, [2018-01-23T08:41:30.792481 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 820, WOS:000223512402213, PubmedSourceRecord failed, PMID: 28016890
E, [2018-01-23T08:48:31.071864 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 834, WOS:000208880301581, PubmedSourceRecord failed, PMID: 28023703
E, [2018-01-23T08:50:24.363649 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 838, WOS:000402122400060, PubmedSourceRecord failed, PMID: 28048861
E, [2018-01-23T08:50:24.822737 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 838, WOS:000402366300058, PubmedSourceRecord failed, PMID: 28046589
E, [2018-01-23T08:50:26.120719 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 838, WOS:000401930600040, PubmedSourceRecord failed, PMID: 28046982
E, [2018-01-23T08:51:33.417398 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 841, WOS:000208880300146, PubmedSourceRecord failed, PMID: 28020777
E, [2018-01-23T08:52:27.654568 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 843, WOS:000223512403169, PubmedSourceRecord failed, PMID: 28014540
E, [2018-01-23T09:01:17.609601 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 856, WOS:000209849300442, PubmedSourceRecord failed, PMID: 27983143
E, [2018-01-23T09:02:18.092551 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 858, WOS:000235246000122, PubmedSourceRecord failed, PMID: 28180490
E, [2018-01-23T09:02:35.400589 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 858, WOS:000235246000115, PubmedSourceRecord failed, PMID: 28180485
E, [2018-01-23T09:02:49.811860 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 858, WOS:000235246000068, PubmedSourceRecord failed, PMID: 28180426
E, [2018-01-23T09:03:28.696464 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 859, WOS:000402425500049, PubmedSourceRecord failed, PMID: 28046308
E, [2018-01-23T09:30:13.052734 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 893, WOS:000239009403362, PubmedSourceRecord failed, PMID: 27954380
E, [2018-01-23T09:31:08.852048 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 893, WOS:000239009403310, PubmedSourceRecord failed, PMID: 27954252
E, [2018-01-23T09:32:01.507893 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 894, WOS:000397332900098, PubmedSourceRecord failed, PMID: 27970266
E, [2018-01-23T09:48:38.823094 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 898, WOS:000276606606006, PubmedSourceRecord failed, PMID: 27961073
E, [2018-01-23T09:48:39.270861 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 898, WOS:000276606605545, PubmedSourceRecord failed, PMID: 27961029
E, [2018-01-23T09:48:39.711455 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 898, WOS:000276606605461, PubmedSourceRecord failed, PMID: 27960987
E, [2018-01-23T09:53:10.955908 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 907, WOS:000208880302015, PubmedSourceRecord failed, PMID: 28020000
E, [2018-01-23T09:53:12.778212 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 907, WOS:000208880302034, PubmedSourceRecord failed, PMID: 28019963
E, [2018-01-23T09:54:14.180781 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 911, WOS:000223512402439, PubmedSourceRecord failed, PMID: 28014498
E, [2018-01-23T10:31:13.186077 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 940, WOS:000336849900371, PubmedSourceRecord failed, PMID: 28519908
E, [2018-01-23T10:35:08.926443 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 946, WOS:000208892400310, PubmedSourceRecord failed, PMID: 27968065
E, [2018-01-23T10:35:09.375725 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 946, WOS:000208880700189, PubmedSourceRecord failed, PMID: 27968481
E, [2018-01-23T10:35:30.846083 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 946, WOS:000208892400259, PubmedSourceRecord failed, PMID: 27968162
E, [2018-01-23T10:36:01.486700 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 946, WOS:000208880700351, PubmedSourceRecord failed, PMID: 27968649
E, [2018-01-23T11:15:12.782623 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1013, WOS:000208880700027, PubmedSourceRecord failed, PMID: 27968389
E, [2018-01-23T11:18:37.154940 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1031, WOS:000398590400047, PubmedSourceRecord failed, PMID: 27969884
E, [2018-01-23T11:18:40.751874 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1031, WOS:000397332900037, PubmedSourceRecord failed, PMID: 27969714
E, [2018-01-23T11:34:37.816937 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1113, WOS:000420910700004, PubmedSourceRecord failed, PMID: 26430959
E, [2018-01-23T12:31:29.063391 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1186, WOS:000415210700039, PubmedSourceRecord failed, PMID: 27360813
E, [2018-01-23T13:03:12.363519 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1222, WOS:000402319800051, PubmedSourceRecord failed, PMID: 28047264
E, [2018-01-23T13:07:47.522144 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1241, WOS:000208892400004, PubmedSourceRecord failed, PMID: 28143336
E, [2018-01-23T13:08:14.154533 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1241, WOS:000208892400200, PubmedSourceRecord failed, PMID: 27968135
E, [2018-01-23T13:40:13.720737 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1293, WOS:A1984TU70100010, PubmedSourceRecord failed, PMID: 6510716
E, [2018-01-23T13:57:58.779110 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1325, WOS:000231111200107, PubmedSourceRecord failed, PMID: 28184762
E, [2018-01-23T15:17:01.600468 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1476, WOS:000208880301040, PubmedSourceRecord failed, PMID: 28021098
E, [2018-01-23T15:45:58.358397 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000402364400030, PubmedSourceRecord failed, PMID: 28047255
E, [2018-01-23T15:46:19.661408 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000336849902212, PubmedSourceRecord failed, PMID: 28524488
E, [2018-01-23T15:46:20.154992 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000402366300051, PubmedSourceRecord failed, PMID: 28048529
E, [2018-01-23T15:46:20.656767 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000336849901220, PubmedSourceRecord failed, PMID: 28519670
E, [2018-01-23T15:46:31.349581 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000402031300056, PubmedSourceRecord failed, PMID: 28048221
E, [2018-01-23T15:46:31.829236 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000402370100050, PubmedSourceRecord failed, PMID: 28046566
E, [2018-01-23T15:46:32.298055 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1568, WOS:000402364400028, PubmedSourceRecord failed, PMID: 28048517
E, [2018-01-23T16:53:58.738135 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1720, WOS:000208880300221, PubmedSourceRecord failed, PMID: 28021259
E, [2018-01-23T18:48:17.303176 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1910, WOS:000402011300034, PubmedSourceRecord failed, PMID: 28048550
E, [2018-01-23T19:53:38.999277 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1997, WOS:000336849900272, PubmedSourceRecord failed, PMID: 28518810
E, [2018-01-23T19:53:39.929487 #16284] ERROR -- : WebOfScience::ProcessRecords: Author: 1997, WOS:000402393300053, PubmedSourceRecord failed, PMID: 28047193
```
