### ISSUE TITLE
Author creation from authors poller fails due to misnamed attribute

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#785]
Discovered when running cap author poller rake task on sul-pub-cap-dev

```E, [2018-03-15T12:52:58.279569 #20910] ERROR -- : #<NameError: undefined local variable or method `auth_hash' for #<Class:0x00000007bb1910>>
E, [2018-03-15T12:52:58.280101 #20910] ERROR -- : /opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/opt/app/pub/sul-pub/releases/20180306224450/app/models/author.rb:135:in `block in fetch_from_cap_and_create'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/core.rb:283:in `initialize'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!''```

**Comment by peetucket** [comment]
```PRODUCTION [2] pry(main)> Author.fetch_from_cap_and_create('88083')
NameError: undefined local variable or method `auth_hash' for #<Class:0x00000007a23918>
from /opt/app/pub/sul-pub/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/dynamic_matchers.rb:26:in `method_missing'```
