### ISSUE TITLE
embargo-release broken

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/sul_pub#91]
See email for context. Here's the exception in test:

```
[lyberadmin@sul-robots1-test ~]$ cd /home/lyberadmin/common-accessioning/current/
[lyberadmin@sul-robots1-test current]$ BUNDLE_GEMFILE=/home/lyberadmin/common-accessioning/current/Gemfile ROBOT_ENVIRONMENT=test /usr/local/rvm/wrappers/default/ruby /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb
Loading config from /home/lyberadmin/common-accessioning/current/config/environments/test
DEPRECATION WARNING: Dor::Config -- solrizer configuration is deprecated. Please use solr instead. (called from <top (required)> at /home/lyberadmin/common-accessioning/current/config/environments/test.rb:3)
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:13: warning: already initialized constant ENABLE_SOLR_UPDATES
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/active-fedora-6.7.3/lib/active_fedora.rb:13: warning: previous definition of ENABLE_SOLR_UPDATES was here
D, [2016-06-07T14:53:16.639176 #1737] DEBUG -- : Loaded datastream list for druid:kn280cs8150 (67.3ms)
D, [2016-06-07T14:53:16.722530 #1737] DEBUG -- : Loaded datastream profile druid:kn280cs8150/RELS-EXT (80.8ms)
D, [2016-06-07T14:53:16.803216 #1737] DEBUG -- : Loaded datastream content druid:kn280cs8150/RELS-EXT (74.5ms)
D, [2016-06-07T14:53:16.885258 #1737] DEBUG -- : Loaded datastream profile druid:kn280cs8150/workflows (76.5ms)
D, [2016-06-07T14:53:21.979189 #1737] DEBUG -- : Loaded datastream list for druid:mt134rb1849 (81.3ms)
D, [2016-06-07T14:53:22.048149 #1737] DEBUG -- : Loaded datastream profile druid:mt134rb1849/RELS-EXT (67.3ms)
D, [2016-06-07T14:53:22.119108 #1737] DEBUG -- : Loaded datastream content druid:mt134rb1849/RELS-EXT (69.2ms)
D, [2016-06-07T14:53:22.180513 #1737] DEBUG -- : Loaded datastream profile druid:mt134rb1849/workflows (59.6ms)
D, [2016-06-07T14:53:22.983316 #1737] DEBUG -- : Loaded datastream list for druid:my974mh9308 (86.0ms)
D, [2016-06-07T14:53:23.089404 #1737] DEBUG -- : Loaded datastream profile druid:my974mh9308/RELS-EXT (103.3ms)
D, [2016-06-07T14:53:23.153832 #1737] DEBUG -- : Loaded datastream content druid:my974mh9308/RELS-EXT (63.4ms)
D, [2016-06-07T14:53:23.227182 #1737] DEBUG -- : Loaded datastream profile druid:my974mh9308/workflows (70.1ms)
D, [2016-06-07T14:53:25.788271 #1737] DEBUG -- : Loaded datastream list for druid:px885wv4511 (83.5ms)
D, [2016-06-07T14:53:25.874638 #1737] DEBUG -- : Loaded datastream profile druid:px885wv4511/RELS-EXT (82.7ms)
D, [2016-06-07T14:53:25.978890 #1737] DEBUG -- : Loaded datastream content druid:px885wv4511/RELS-EXT (102.4ms)
D, [2016-06-07T14:53:26.065019 #1737] DEBUG -- : Loaded datastream profile druid:px885wv4511/workflows (83.1ms)
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:561:in `rescue in workflow_resource_method': Failed to retrieve resource: put https://lyberservices-test.stanford.edu/workflow//dor/objects/druid:px885wv4511/workflows/disseminationWF/embargo-release (HTTP status 500) (Dor::WorkflowException)
from /home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:551:in `workflow_resource_method'
from /home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:162:in `update_workflow_error_status'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:49:in `rescue in block in release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:37:in `block in release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `each'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:57:in `release'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:67:in `<main>’
```

**Comment by peetucket** [comment]
turns out there was already a proxy issue for this in the media project...closing this one...

see https://github.com/sul-dlss/media/issues/68
